name: build-win-stcp
on:
  workflow_dispatch:
jobs:
  build-win:
    name: Build hbbs/hbbr (Windows, STCP)
    runs-on: windows-2022
    steps:
      - name: Clone upstream stcp branch
        shell: bash
        run: |
          git clone --depth 1 --branch stcp https://github.com/IamTaoChen/rustdesk-server.git .
      - name: Install Rust 1.70.0 (x86_64-pc-windows-msvc)
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.70.0'
          targets: x86_64-pc-windows-msvc
      - name: Build hbbs / hbbr / rustdesk-utils
        run: cargo build --release --all-features --target x86_64-pc-windows-msvc
        shell: bash
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-server-stcp-windows
          path: |
            target/x86_64-pc-windows-msvc/release/hbbs.exe
            target/x86_64-pc-windows-msvc/release/hbbr.exe
            target/x86_64-pc-windows-msvc/release/rustdesk-utils.exe
          if-no-files-found: error
